app/__init__.py
from flask import Flask, url_for
from flask_bootstrap import Bootstrap
from config import Config

def create_app(config_class=Config):
    app = Flask(__name__, static_folder='static')
    bootstrap = Bootstrap(app)
    app.config.from_object(config_class)
    app.config['UPLOAD_FOLDER'] = 'static'
    # Initialize Flask extensions here

    # Register blueprints here
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.posts import bp as post_bp
    app.register_blueprint(post_bp, url_prefix='/posts')

    @app.route('/test/')
    def test_page():
        return '<h1>Flask Folder Structure Pattern</h1>'

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import render_template, url_for

@bp.route('/')
def index():
    return render_template("index.html")

@bp.route('/about')
def about():
    return render_template("about.html")

app/posts/__init__.py
from flask import Blueprint

bp = Blueprint('posts', __name__)

from app.posts import routes

app/posts/routes.py
from flask import render_template
from app.posts import bp

@bp.route('/')
def index():
    return "<h1>Flask Posts Route</h1>"

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="ftco-blocks-cover-1">
<div class="site-section-cover overlay" style="background-image: url('{{ url_for('static', filename='images/hero_1.jpg') }}');">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-5" data-aos="fade-up">
        <h1 class="mb-3 text-white">About Us</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta veritatis in tenetur doloremque, maiores doloribus officia iste. Dolores.</p>

      </div>
    </div>
  </div>
</div>
</div>

<div class="site-section py-5">
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-6">
      <div class="heading-39101 mb-5">
        <span class="backdrop">Story</span>
        <span class="subtitle-39191">Discover Story</span>
        <h3>Our Story</h3>
      </div>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi quae expedita fugiat quo incidunt, possimus temporibus aperiam eum, quaerat sapiente.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos debitis enim a pariatur molestiae.</p>
    </div>
    <div class="col-md-6" data-aos="fade-right">
      <img src="{{ url_for('static', filename='images/traveler.jpg') }}" alt="Image" class="img-fluid">
    </div>
  </div>
</div>
</div>

<div class="site-section py-5">
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-5 order-2 ml-auto">
      <div class="heading-39101 mb-5">
        <span class="backdrop">Mission</span>
        <span class="subtitle-39191">Our Mission</span>
        <h3>Our Mission</h3>
      </div>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi quae expedita fugiat quo incidunt, possimus temporibus aperiam eum, quaerat sapiente.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos debitis enim a pariatur molestiae.</p>
    </div>
    <div class="col-md-6 order-1" data-aos="fade-left">
      <img src="{{ url_for('static', filename='images/hero_1.jpg') }}" alt="Image" class="img-fluid">
    </div>
  </div>
</div>
</div>

<div class="site-section">

<div class="container">
  <div class="row justify-content-center text-center">
    <div class="col-md-10">
      <div class="heading-39101 mb-5">
        <span class="backdrop text-center">Our Team</span>
        <span class="subtitle-39191">Amazing Staff</span>
        <h3>Meet Our Team</h3>
      </div>
    </div>
  </div>


  <div class="row">

    <div class="col-lg-4 col-md-6 mb-4">
      <div class="person-29191 text-center">
        <img src="{{ url_for('static', filename='images/person_1.jpg') }}" alt="Image" class="img-fluid mb-4">
        <div class="px-4">
          <h2 class="mb-2">John Doe</h2>
          <p class="caption mb-4">Staff</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae, maiores? Eos alias fugit eius, repudiandae molestias error</p>
          <div class="social_29128 mt-5">
          <a href="#"><span class="icon-facebook"></span></a>
          <a href="#"><span class="icon-instagram"></span></a>
          <a href="#"><span class="icon-twitter"></span></a>
         </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4 col-md-6 mb-4">
      <div class="person-29191 text-center">
        <img src="{{ url_for('static', filename='images/person_2.jpg') }}" alt="Image" class="img-fluid mb-4">
        <div class="px-4">
          <h2 class="mb-2">Jean Doe</h2>
          <p class="caption mb-4">Staff</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae, maiores? Eos alias fugit eius, repudiandae molestias error</p>
          <div class="social_29128 mt-5">
          <a href="#"><span class="icon-facebook"></span></a>
          <a href="#"><span class="icon-instagram"></span></a>
          <a href="#"><span class="icon-twitter"></span></a>
         </div>
        </div>
      </div>
    </div>

    <div class="col-lg-4 col-md-6 mb-4">
      <div class="person-29191 text-center">
        <img src="{{ url_for('static', filename='images/person_3.jpg') }}" alt="Image" class="img-fluid mb-4">
        <div class="px-4">
          <h2 class="mb-2">Claire Dormey</h2>
          <p class="caption mb-4">Staff</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae, maiores? Eos alias fugit eius, repudiandae molestias error</p>
          <div class="social_29128 mt-5">
          <a href="#"><span class="icon-facebook"></span></a>
          <a href="#"><span class="icon-instagram"></span></a>
          <a href="#"><span class="icon-twitter"></span></a>
         </div>
        </div>
      </div>
    </div>

  </div>

</div>
</div>

<div class="site-section bg-image overlay" style="background-image: url('{{ url_for('static', filename='images/hero_1.jpg') }}');">
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-7 text-center">
      <h2 class="font-weight-bold text-white">Join and Trip With Us</h2>
      <p class="text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus ut, doloremque quo molestiae nesciunt officiis veniam, beatae dignissimos!</p>
      <p class="mb-0"><a href="#" class="btn btn-primary text-white py-3 px-4">Get In Touch</a></p>
    </div>
  </div>
</div>
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <title>{% block title %} - {% endblock %} Flask</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,700,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/icomoon/style.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datepicker.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.fancybox.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.carousel.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/owl.theme.default.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/flaticon/font/flaticon.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/aos.css') }}">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">


    <div class="site-wrap" id="home-section">

      <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>



      <header class="site-navbar site-navbar-target" role="banner">

        <div class="container">
          <div class="row align-items-center position-relative">

            <div class="col-3 ">
              <div class="site-logo">
                <a href="{{ url_for('main.index') }}" class="font-weight-bold">
                  <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Image" class="img-fluid">
                </a>
              </div>
            </div>

            <div class="col-9  text-right">


              <span class="d-inline-block d-lg-none"><a href="#" class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span class="icon-menu h3 text-white"></span></a></span>



              <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                  <li class="active"><a href="{{ url_for('main.index') }}" class="nav-link">Home</a></li>
                  <li><a href="{{ url_for('main.about') }}" class="nav-link">About</a></li>
                  <li><a href="trips.html" class="nav-link">Trips</a></li>
                  <li><a href="blog.html" class="nav-link">Blog</a></li>
                  <li><a href="contact.html" class="nav-link">Contact</a></li>
                </ul>
              </nav>
            </div>


          </div>
        </div>

      </header>

    {% block content %} {% endblock %}

    <footer class="site-footer bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-3">
            <h2 class="footer-heading mb-3">Instagram</h2>
            <div class="row">
              <div class="col-4 gal_col">
                <a href="#"><img src="{{ url_for('static', filename='images/insta_1.jpg') }}" alt="Image" class="img-fluid"></a>
              </div>
              <div class="col-4 gal_col">
                <a href="#"><img src="{{ url_for('static', filename='images/insta_2.jpg') }}" alt="Image" class="img-fluid"></a>
              </div>
              <div class="col-4 gal_col">
                <a href="#"><img src="{{ url_for('static', filename='images/insta_3.jpg') }}" alt="Image" class="img-fluid"></a>
              </div>
              <div class="col-4 gal_col">
                <a href="#"><img src="{{ url_for('static', filename='images/insta_4.jpg') }}" alt="Image" class="img-fluid"></a>
              </div>
              <div class="col-4 gal_col">
                <a href="#"><img src="{{ url_for('static', filename='images/insta_5.jpg') }}" alt="Image" class="img-fluid"></a>
              </div>
              <div class="col-4 gal_col">
                <a href="#"><img src="{{ url_for('static', filename='images/insta_6.jpg') }}" alt="Image" class="img-fluid"></a>
              </div>
            </div>
          </div>
          <div class="col-lg-8 ml-auto">
            <div class="row">
              <div class="col-lg-6 ml-auto">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Testimonials</a></li>
                  <li><a href="#">Terms of Service</a></li>
                  <li><a href="#">Privacy</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-lg-6">
                <h2 class="footer-heading mb-4">Newsletter</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nesciunt odio iure animi ullam quam, deleniti rem!</p>
                <form action="#" class="d-flex" class="subscribe">
                  <input type="text" class="form-control mr-3" placeholder="Email">
                  <input type="submit" value="Send" class="btn btn-primary">
                </form>
              </div>

            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
              <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
            </div>
          </div>

        </div>
      </div>
    </footer>

    </div>

    <script src="{{ url_for('static', filename='js/jquery-3.3.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery-migrate-3.0.0.js') }}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/owl.carousel.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.sticky.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.waypoints.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.animateNumber.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.fancybox.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.stellar.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.easing.1.3.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/isotope.pkgd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/aos.js') }}"></script>

    <script src="{{ url_for('static', filename='js/main.js') }}"></script>

  </body>

</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="ftco-blocks-cover-1">
      <div class="site-section-cover overlay" style="background-image: url('images/hero_1.jpg')">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-md-5" data-aos="fade-right">
              <h1 class="mb-3 text-white">Let's Enjoy The Wonders of Nature</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta veritatis in tenetur doloremque, maiores doloribus officia iste. Dolores.</p>
              <p class="d-flex align-items-center">
                <a href="https://vimeo.com/191947042" data-fancybox class="play-btn-39282 mr-3"><span class="icon-play"></span></a>
                <span class="small">Watch the video</span>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="site-section py-5">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6">
            <div class="heading-39101 mb-5">
              <span class="backdrop">Story</span>
              <span class="subtitle-39191">Discover Story</span>
              <h3>Our Story</h3>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi quae expedita fugiat quo incidunt, possimus temporibus aperiam eum, quaerat sapiente.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos debitis enim a pariatur molestiae.</p>
          </div>
          <div class="col-md-6" data-aos="fade-right">
            <img src="{{ url_for('static', filename='images/traveler.jpg') }}" alt="Image" class="img-fluid">
          </div>
        </div>
      </div>
    </div>

    <div class="site-section">

      <div class="container">
        <div class="row justify-content-center text-center">
          <div class="col-md-7">
            <div class="heading-39101 mb-5">
              <span class="backdrop text-center">Journey</span>
              <span class="subtitle-39191">Journey</span>
              <h3>Your Journey Starts Here</h3>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 col-md-6 mb-4" data-aos="fade-up">
            <div class="listing-item">
              <div class="listing-image">
                <img src="{{ url_for('static', filename='images/img_1.jpg') }}" alt="Image" class="img-fluid">
              </div>
              <div class="listing-item-content">
                <a class="px-3 mb-3 category bg-primary" href="#">$200.00</a>
                <h2 class="mb-1"><a href="trip-single.html">Dignissimos debitis</a></h2>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4" data-aos="fade-up">
            <div class="listing-item">
              <div class="listing-image">
                <img src="{{ url_for('static', filename='images/img_2.jpg') }}" alt="Image" class="img-fluid">
              </div>
              <div class="listing-item-content">
                <a class="px-3 mb-3 category bg-primary" href="#">$390.00</a>
                <h2 class="mb-1"><a href="trip-single.html">Consectetur adipisicing</a></h2>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4" data-aos="fade-up">
            <div class="listing-item">
              <div class="listing-image">
                <img src="{{ url_for('static', filename='images/img_3.jpg') }}" alt="Image" class="img-fluid">
              </div>
              <div class="listing-item-content">
                <a class="px-3 mb-3 category bg-primary" href="#">$180.00</a>
                <h2 class="mb-1"><a href="trip-single.html">Temporibus aperiam</a></h2>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4" data-aos="fade-up">
            <div class="listing-item">
              <div class="listing-image">
                <img src="{{ url_for('static', filename='images/img_4.jpg') }}" alt="Image" class="img-fluid">
              </div>
              <div class="listing-item-content">
                <a class="px-3 mb-3 category bg-primary" href="#">$600.00</a>
                <h2 class="mb-1"><a href="trip-single.html">Expedita fugiat</a></h2>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4" data-aos="fade-up">
            <div class="listing-item">
              <div class="listing-image">
                <img src="{{ url_for('static', filename='images/img_5.jpg') }}" alt="Image" class="img-fluid">
              </div>
              <div class="listing-item-content">
                <a class="px-3 mb-3 category bg-primary" href="#">$330.00</a>
                <h2 class="mb-1"><a href="trip-single.html">Consectetur adipisicing</a></h2>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4" data-aos="fade-up">
            <div class="listing-item">
              <div class="listing-image">
                <img src="{{ url_for('static', filename='images/img_6.jpg') }}" alt="Image" class="img-fluid">
              </div>
              <div class="listing-item-content">
                <a class="px-3 mb-3 category bg-primary" href="#">$450.00</a>
                <h2 class="mb-1"><a href="trip-single.html">Consectetur Amet</a></h2>
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>

    <div class="site-section">

      <div class="container">
        <div class="row justify-content-center text-center">
          <div class="col-md-10">
            <div class="heading-39101 mb-5">
              <span class="backdrop text-center">Our Team</span>
              <span class="subtitle-39191">Amazing Staff</span>
              <h3>Meet Our Team</h3>
            </div>
          </div>
        </div>


        <div class="row">

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="person-29191 text-center">
              <img src="{{ url_for('static', filename='images/person_1.jpg') }}" alt="Image" class="img-fluid mb-4">
              <div class="px-4">
                <h2 class="mb-2">John Doe</h2>
                <p class="caption mb-4">Staff</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae, maiores? Eos alias fugit eius, repudiandae molestias error</p>
                <div class="social_29128 mt-5">
                <a href="#"><span class="icon-facebook"></span></a>
                <a href="#"><span class="icon-instagram"></span></a>
                <a href="#"><span class="icon-twitter"></span></a>
               </div>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="person-29191 text-center">
              <img src="{{ url_for('static', filename='images/person_2.jpg') }}" alt="Image" class="img-fluid mb-4">
              <div class="px-4">
                <h2 class="mb-2">Jean Doe</h2>
                <p class="caption mb-4">Staff</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae, maiores? Eos alias fugit eius, repudiandae molestias error</p>
                <div class="social_29128 mt-5">
                <a href="#"><span class="icon-facebook"></span></a>
                <a href="#"><span class="icon-instagram"></span></a>
                <a href="#"><span class="icon-twitter"></span></a>
               </div>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="person-29191 text-center">
              <img src="{{ url_for('static', filename='images/person_3.jpg') }}" alt="Image" class="img-fluid mb-4">
              <div class="px-4">
                <h2 class="mb-2">Claire Dormey</h2>
                <p class="caption mb-4">Staff</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestiae, maiores? Eos alias fugit eius, repudiandae molestias error</p>
                <div class="social_29128 mt-5">
                <a href="#"><span class="icon-facebook"></span></a>
                <a href="#"><span class="icon-instagram"></span></a>
                <a href="#"><span class="icon-twitter"></span></a>
               </div>
              </div>
            </div>
          </div>

        </div>

      </div>
    </div>



{% endblock %}